# 应用名称
name: ris-examples
# 开发测试环境, dev/pro
mode: dev
# 版本信息
version: 0.0.1

# listen
listen: ":8800"

# 数据库
mysql: ./config/mysql.yaml
sqlite: ./config/sqlite.yaml

# 日志级别, disable|fatal|error|warn|info|debug
level: debug
# 日志配置
logger: ./config/logger.yaml

# 业务配置
business: ./config/business.yaml
